### PR TITLE
Update to re-render when svgXmlData and fill props change

### PR DESCRIPTION
**Pull request by ruifreitas**
This PR does the following:
- It updates the component to re-render when the `svgXmlData` and `fill` props change.
- Fix the svg `width` and `height` attrs missing.

### CODE REVIEW

**Comment by SandroMachado** [comment]
@matc4 any plans to merge this?

**Comment by matc4** [comment]
Hello @SandroMachado ,
I have a doubt with this PR:

> It updates the component to re-render when the svgXmlData and fill props change.

Is not working already in this way?

**Comment by SandroMachado** [comment]
Hi @matc4,

unfortunately not. If we change the `svgXmlData` or the `fill` prop after the instantiation of the component, it does not change it. We need to update the state in the method `componentWillReceiveProps`. 

Regards

**Comment by srounce** [comment]
Any update on this PR?

**Comment by SandroMachado** [comment]
@matc4 sorry to bother you again but can you please take a look at this PR.

**Comment by beilunyang** [comment]
I also meet the bug, please merge this PR...

**Comment by matc4** [comment]
Thanks @ruifreitas !

**Pull request merged**
