### PR TITLE
support expo

### PR DESCRIPTION
**Pull request by gaboelnuevo**

### CODE REVIEW

**Comment by ezhlobo** [comment]
@vault-development hey, can we think about this changes? What do you need to make it merged?

**Comment by gaboelnuevo** [comment]
I found an issue with current React-Native versions please test it before

**Comment by ezhlobo** [comment]
@gaboelnuevo could you provide more details, please? I'm going to use this library.

**Comment by gaboelnuevo** [comment]
@ezhlobo I encounter a error while testing in react-native ^0.52.2 but in expo works very well

**Comment by gaboelnuevo** [comment]
I think that some configurations of babel presets throw an error when required failed.

**Comment by joao-conde** [comment]
How about merging this? Seems to be properly working?

**Comment by nathsimpson** [comment]
When will this be merged???

**Comment by sandersjj** [comment]
I can confirm that this fix works for me.

**Comment by keeth** [comment]
confirmed.  please merge.

**Comment by obiwankenoobi** [comment]
why its not merged?

**Comment by gaboelnuevo** [comment]
In new versions of Expo this commit is unnecessary and deprecated. (SDK >= v33.0.0)

**Comment by msand** [comment]
You can use SvgUri from react-native-svg nowadays instead. No need for react-native-svg-uri.

**Pull request closed without merging**
