### PR TITLE
Fix: Text elements / transform + clipPath attribute added

### PR DESCRIPTION
**Pull request by nesc58**
Hi,
here is a fix for the text element.

Commit: bc85a03
I think `trim().length` should be called instead of `trim.length`... all strings were filtered out.

Commit: 7f9c13f
added textAnchor to improve the alignment of text elements.
added transform e.g. to rotate an element
added clipPath to define clipping for an element.

Commit: 50ed807
removed unnecessary call of fixYPosition. There is nothing to fix when textAnchor used in the svg.

For me this fix works like a charm.

### CODE REVIEW

**Comment by vintage** [comment]
Thanks a lot, the `transform` functionality works like a charm! @vault-development any news about merging it into the upstream?

**Comment by jrob-io** [comment]
Confirming that `transform` works using: 

```
"react-native": "0.55.3"
"react-native-svg": "^6.3.1"
"react-native-svg-uri": "https://github.com/nesc58/react-native-svg-uri"
```

**Comment by robinbiondi** [comment]
Hello there! I would love to see this modification released. Do you think you will merge it ?

**Comment by matc4** [comment]
Merged!

**Comment by cadesalaberry** [comment]
Great! Will you publish a new version on the npm registry anytime soon?

**Pull request merged**
